export const RESERVED_GAME_NUMBER = 1;
export const DRAFTABLE_GAME_COUNT = 80;
export const DEADLINE_LABEL = "Wednesday, March 18th";
export const STADIUM_LABEL = "Globe Life Field - Arlington";
export const OUTLOOK_LOCATION = "Globe Life Field, 734 Stadium Dr, Arlington, TX 76011";

export const MEMBER_SEED_DATA = [
  { name: "George", share_count: 32, rank_max: 50, accent_color: "#C0111F" },
  { name: "Sandy", share_count: 24, rank_max: 50, accent_color: "#003278" },
  { name: "Clark", share_count: 9, rank_max: 20, accent_color: "#BFA048" },
  { name: "Ed", share_count: 7, rank_max: 20, accent_color: "#1D428A" },
  { name: "Chase", share_count: 8, rank_max: 20, accent_color: "#8B1A1A" }
];

export const GAME_SEED_DATA = [
  { game_number: 1, date: "2026-04-03", day_of_week: "Fri", start_time: "3:05 PM", start_time_et: "4:05 PM", opponent: "Reds", month: "April", location: STADIUM_LABEL, is_day_game: true, is_holiday: "Opening Day", promotional_event: "" },
  { game_number: 2, date: "2026-04-04", day_of_week: "Sat", start_time: "6:05 PM", start_time_et: "7:05 PM", opponent: "Reds", month: "April", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "Fireworks Night" },
  { game_number: 3, date: "2026-04-05", day_of_week: "Sun", start_time: "1:35 PM", start_time_et: "2:35 PM", opponent: "Reds", month: "April", location: STADIUM_LABEL, is_day_game: true, is_holiday: "", promotional_event: "Kids Day" },
  { game_number: 4, date: "2026-04-06", day_of_week: "Mon", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Mariners", month: "April", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 5, date: "2026-04-07", day_of_week: "Tue", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Mariners", month: "April", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 6, date: "2026-04-08", day_of_week: "Wed", start_time: "1:35 PM", start_time_et: "2:35 PM", opponent: "Mariners", month: "April", location: STADIUM_LABEL, is_day_game: true, is_holiday: "", promotional_event: "" },
  { game_number: 7, date: "2026-04-21", day_of_week: "Tue", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Pirates", month: "April", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 8, date: "2026-04-22", day_of_week: "Wed", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Pirates", month: "April", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 9, date: "2026-04-23", day_of_week: "Thu", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Pirates", month: "April", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 10, date: "2026-04-24", day_of_week: "Fri", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Athletics", month: "April", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "Fireworks Night" },
  { game_number: 11, date: "2026-04-25", day_of_week: "Sat", start_time: "6:05 PM", start_time_et: "7:05 PM", opponent: "Athletics", month: "April", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "Bobblehead Giveaway" },
  { game_number: 12, date: "2026-04-26", day_of_week: "Sun", start_time: "1:35 PM", start_time_et: "2:35 PM", opponent: "Athletics", month: "April", location: STADIUM_LABEL, is_day_game: true, is_holiday: "", promotional_event: "Kids Day" },
  { game_number: 13, date: "2026-04-27", day_of_week: "Mon", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Yankees", month: "April", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 14, date: "2026-04-28", day_of_week: "Tue", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Yankees", month: "April", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 15, date: "2026-04-29", day_of_week: "Wed", start_time: "1:35 PM", start_time_et: "2:35 PM", opponent: "Yankees", month: "April", location: STADIUM_LABEL, is_day_game: true, is_holiday: "", promotional_event: "" },
  { game_number: 16, date: "2026-05-08", day_of_week: "Fri", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Cubs", month: "May", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "Fireworks Night" },
  { game_number: 17, date: "2026-05-09", day_of_week: "Sat", start_time: "6:05 PM", start_time_et: "7:05 PM", opponent: "Cubs", month: "May", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "Bobblehead Giveaway" },
  { game_number: 18, date: "2026-05-10", day_of_week: "Sun", start_time: "1:35 PM", start_time_et: "2:35 PM", opponent: "Cubs", month: "May", location: STADIUM_LABEL, is_day_game: true, is_holiday: "Mother's Day", promotional_event: "" },
  { game_number: 19, date: "2026-05-11", day_of_week: "Mon", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "D-backs", month: "May", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 20, date: "2026-05-12", day_of_week: "Tue", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "D-backs", month: "May", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 21, date: "2026-05-13", day_of_week: "Wed", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "D-backs", month: "May", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 22, date: "2026-05-25", day_of_week: "Mon", start_time: "6:05 PM", start_time_et: "7:05 PM", opponent: "Astros", month: "May", location: STADIUM_LABEL, is_day_game: false, is_holiday: "Memorial Day", promotional_event: "" },
  { game_number: 23, date: "2026-05-26", day_of_week: "Tue", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Astros", month: "May", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 24, date: "2026-05-27", day_of_week: "Wed", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Astros", month: "May", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 25, date: "2026-05-28", day_of_week: "Thu", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Astros", month: "May", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 26, date: "2026-05-29", day_of_week: "Fri", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Royals", month: "May", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "Fireworks Night" },
  { game_number: 27, date: "2026-05-30", day_of_week: "Sat", start_time: "3:05 PM", start_time_et: "4:05 PM", opponent: "Royals", month: "May", location: STADIUM_LABEL, is_day_game: true, is_holiday: "", promotional_event: "" },
  { game_number: 28, date: "2026-05-31", day_of_week: "Sun", start_time: "1:35 PM", start_time_et: "2:35 PM", opponent: "Royals", month: "May", location: STADIUM_LABEL, is_day_game: true, is_holiday: "", promotional_event: "Kids Day" },
  { game_number: 29, date: "2026-06-05", day_of_week: "Fri", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Guardians", month: "June", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "Fireworks Night" },
  { game_number: 30, date: "2026-06-06", day_of_week: "Sat", start_time: "6:35 PM", start_time_et: "7:35 PM", opponent: "Guardians", month: "June", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "Bobblehead Giveaway" },
  { game_number: 31, date: "2026-06-07", day_of_week: "Sun", start_time: "1:35 PM", start_time_et: "2:35 PM", opponent: "Guardians", month: "June", location: STADIUM_LABEL, is_day_game: true, is_holiday: "", promotional_event: "Kids Day" },
  { game_number: 32, date: "2026-06-15", day_of_week: "Mon", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Twins", month: "June", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 33, date: "2026-06-16", day_of_week: "Tue", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Twins", month: "June", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 34, date: "2026-06-18", day_of_week: "Thu", start_time: "1:35 PM", start_time_et: "2:35 PM", opponent: "Twins", month: "June", location: STADIUM_LABEL, is_day_game: true, is_holiday: "", promotional_event: "" },
  { game_number: 35, date: "2026-06-19", day_of_week: "Fri", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Padres", month: "June", location: STADIUM_LABEL, is_day_game: false, is_holiday: "Juneteenth", promotional_event: "Fireworks Night" },
  { game_number: 36, date: "2026-06-20", day_of_week: "Sat", start_time: "3:05 PM", start_time_et: "4:05 PM", opponent: "Padres", month: "June", location: STADIUM_LABEL, is_day_game: true, is_holiday: "", promotional_event: "" },
  { game_number: 37, date: "2026-06-21", day_of_week: "Sun", start_time: "1:35 PM", start_time_et: "2:35 PM", opponent: "Padres", month: "June", location: STADIUM_LABEL, is_day_game: true, is_holiday: "Father's Day", promotional_event: "" },
  { game_number: 38, date: "2026-07-02", day_of_week: "Thu", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Tigers", month: "July", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 39, date: "2026-07-04", day_of_week: "Sat", start_time: "3:05 PM", start_time_et: "4:05 PM", opponent: "Tigers", month: "July", location: STADIUM_LABEL, is_day_game: true, is_holiday: "July 4th", promotional_event: "Fireworks Night" },
  { game_number: 40, date: "2026-07-05", day_of_week: "Sun", start_time: "2:30 PM", start_time_et: "3:30 PM", opponent: "Tigers", month: "July", location: STADIUM_LABEL, is_day_game: true, is_holiday: "", promotional_event: "Kids Day" },
  { game_number: 41, date: "2026-07-07", day_of_week: "Tue", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Angels", month: "July", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 42, date: "2026-07-08", day_of_week: "Wed", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Angels", month: "July", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 43, date: "2026-07-09", day_of_week: "Thu", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Angels", month: "July", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 44, date: "2026-07-10", day_of_week: "Fri", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Astros", month: "July", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "Fireworks Night" },
  { game_number: 45, date: "2026-07-11", day_of_week: "Sat", start_time: "6:05 PM", start_time_et: "7:05 PM", opponent: "Astros", month: "July", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "Bobblehead Giveaway" },
  { game_number: 46, date: "2026-07-12", day_of_week: "Sun", start_time: "1:35 PM", start_time_et: "2:35 PM", opponent: "Astros", month: "July", location: STADIUM_LABEL, is_day_game: true, is_holiday: "", promotional_event: "Kids Day" },
  { game_number: 47, date: "2026-07-20", day_of_week: "Mon", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "White Sox", month: "July", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 48, date: "2026-07-21", day_of_week: "Tue", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "White Sox", month: "July", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 49, date: "2026-07-22", day_of_week: "Wed", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "White Sox", month: "July", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 50, date: "2026-07-24", day_of_week: "Fri", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Mariners", month: "July", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "Fireworks Night" },
  { game_number: 51, date: "2026-07-25", day_of_week: "Sat", start_time: "6:15 PM", start_time_et: "7:15 PM", opponent: "Mariners", month: "July", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "Bobblehead Giveaway" },
  { game_number: 52, date: "2026-07-26", day_of_week: "Sun", start_time: "1:35 PM", start_time_et: "2:35 PM", opponent: "Mariners", month: "July", location: STADIUM_LABEL, is_day_game: true, is_holiday: "", promotional_event: "Kids Day" },
  { game_number: 53, date: "2026-07-27", day_of_week: "Mon", start_time: "1:35 PM", start_time_et: "2:35 PM", opponent: "Mariners", month: "July", location: STADIUM_LABEL, is_day_game: true, is_holiday: "", promotional_event: "" },
  { game_number: 54, date: "2026-08-03", day_of_week: "Mon", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Giants", month: "August", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 55, date: "2026-08-04", day_of_week: "Tue", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Giants", month: "August", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 56, date: "2026-08-05", day_of_week: "Wed", start_time: "1:35 PM", start_time_et: "2:35 PM", opponent: "Giants", month: "August", location: STADIUM_LABEL, is_day_game: true, is_holiday: "", promotional_event: "" },
  { game_number: 57, date: "2026-08-07", day_of_week: "Fri", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Orioles", month: "August", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "Fireworks Night" },
  { game_number: 58, date: "2026-08-08", day_of_week: "Sat", start_time: "6:15 PM", start_time_et: "7:15 PM", opponent: "Orioles", month: "August", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "Bobblehead Giveaway" },
  { game_number: 59, date: "2026-08-09", day_of_week: "Sun", start_time: "1:35 PM", start_time_et: "2:35 PM", opponent: "Orioles", month: "August", location: STADIUM_LABEL, is_day_game: true, is_holiday: "", promotional_event: "Kids Day" },
  { game_number: 60, date: "2026-08-18", day_of_week: "Tue", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Nationals", month: "August", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 61, date: "2026-08-19", day_of_week: "Wed", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Nationals", month: "August", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 62, date: "2026-08-20", day_of_week: "Thu", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Nationals", month: "August", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 63, date: "2026-08-21", day_of_week: "Fri", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Angels", month: "August", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "Fireworks Night" },
  { game_number: 64, date: "2026-08-22", day_of_week: "Sat", start_time: "6:05 PM", start_time_et: "7:05 PM", opponent: "Angels", month: "August", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "Bobblehead Giveaway" },
  { game_number: 65, date: "2026-08-23", day_of_week: "Sun", start_time: "1:35 PM", start_time_et: "2:35 PM", opponent: "Angels", month: "August", location: STADIUM_LABEL, is_day_game: true, is_holiday: "", promotional_event: "Kids Day" },
  { game_number: 66, date: "2026-08-31", day_of_week: "Mon", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Athletics", month: "August", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 67, date: "2026-09-01", day_of_week: "Tue", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Athletics", month: "September", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 68, date: "2026-09-02", day_of_week: "Wed", start_time: "1:35 PM", start_time_et: "2:35 PM", opponent: "Athletics", month: "September", location: STADIUM_LABEL, is_day_game: true, is_holiday: "", promotional_event: "" },
  { game_number: 69, date: "2026-09-03", day_of_week: "Thu", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Rays", month: "September", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 70, date: "2026-09-04", day_of_week: "Fri", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Rays", month: "September", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "Fireworks Night" },
  { game_number: 71, date: "2026-09-05", day_of_week: "Sat", start_time: "6:05 PM", start_time_et: "7:05 PM", opponent: "Rays", month: "September", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "Bobblehead Giveaway" },
  { game_number: 72, date: "2026-09-06", day_of_week: "Sun", start_time: "1:35 PM", start_time_et: "2:35 PM", opponent: "Rays", month: "September", location: STADIUM_LABEL, is_day_game: true, is_holiday: "Labor Day Weekend", promotional_event: "" },
  { game_number: 73, date: "2026-09-15", day_of_week: "Tue", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Red Sox", month: "September", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 74, date: "2026-09-16", day_of_week: "Wed", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Red Sox", month: "September", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 75, date: "2026-09-17", day_of_week: "Thu", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Red Sox", month: "September", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 76, date: "2026-09-18", day_of_week: "Fri", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Blue Jays", month: "September", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "Fireworks Night" },
  { game_number: 77, date: "2026-09-19", day_of_week: "Sat", start_time: "6:05 PM", start_time_et: "7:05 PM", opponent: "Blue Jays", month: "September", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "Fan Appreciation Night" },
  { game_number: 78, date: "2026-09-20", day_of_week: "Sun", start_time: "1:35 PM", start_time_et: "2:35 PM", opponent: "Blue Jays", month: "September", location: STADIUM_LABEL, is_day_game: true, is_holiday: "", promotional_event: "Kids Day" },
  { game_number: 79, date: "2026-09-22", day_of_week: "Tue", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Mets", month: "September", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 80, date: "2026-09-23", day_of_week: "Wed", start_time: "7:05 PM", start_time_et: "8:05 PM", opponent: "Mets", month: "September", location: STADIUM_LABEL, is_day_game: false, is_holiday: "", promotional_event: "" },
  { game_number: 81, date: "2026-09-24", day_of_week: "Thu", start_time: "1:35 PM", start_time_et: "2:35 PM", opponent: "Mets", month: "September", location: STADIUM_LABEL, is_day_game: true, is_holiday: "", promotional_event: "Season Finale" }
];

export const MONTH_OPTIONS = ["All", "April", "May", "June", "July", "August", "September"];
export const DAY_OPTIONS = ["All", "Fri", "Sat", "Sun", "Mon", "Tue", "Wed", "Thu"];

export const TEAM_COLORS = {
  Reds: "#C6011F",
  Mariners: "#0C2C56",
  Pirates: "#FDB827",
  Athletics: "#003831",
  Yankees: "#003087",
  Cubs: "#0E3386",
  "D-backs": "#A71930",
  Astros: "#EB6E1F",
  Royals: "#004687",
  Guardians: "#00385D",
  Twins: "#002B5C",
  Padres: "#2F241D",
  Tigers: "#0C2340",
  Angels: "#BA0021",
  "White Sox": "#27251F",
  Giants: "#FD5A1E",
  Orioles: "#DF4601",
  Nationals: "#AB0003",
  Rays: "#092C5C",
  "Red Sox": "#BD3039",
  "Blue Jays": "#134A8E",
  Mets: "#002D72"
};

export const TEAM_ABBREVIATIONS = {
  Reds: "RED",
  Mariners: "SEA",
  Pirates: "PIT",
  Athletics: "ATH",
  Yankees: "NYY",
  Cubs: "CUB",
  "D-backs": "ARI",
  Astros: "AST",
  Royals: "ROY",
  Guardians: "GUA",
  Twins: "MIN",
  Padres: "SDP",
  Tigers: "DET",
  Angels: "LAA",
  "White Sox": "SOX",
  Giants: "SFG",
  Orioles: "BAL",
  Nationals: "WSH",
  Rays: "RAY",
  "Red Sox": "RSX",
  "Blue Jays": "TOR",
  Mets: "NYM"
};